name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    name: "WP ${{ matrix.config.wp }}, multisite: ${{ matrix.config.ms }}, PHP: ${{ matrix.config.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { wp: latest,  ms: 'no',  php: '8.1', coverage: 'yes' }
          - { wp: latest,  ms: 'yes', php: '8.1', coverage: 'yes' }
          - { wp: nightly, ms: 'no',  php: '8.1' }
          - { wp: nightly, ms: 'yes', php: '8.1' }

          - { wp: latest,  ms: 'no',  php: '8.2' }
          - { wp: latest,  ms: 'yes', php: '8.2' }
          - { wp: nightly, ms: 'no',  php: '8.2' }
          - { wp: nightly, ms: 'yes', php: '8.2' }

          - { wp: latest,  ms: 'no',  php: '8.3' }
          - { wp: latest,  ms: 'yes', php: '8.3' }
          - { wp: nightly, ms: 'no',  php: '8.3' }
          - { wp: nightly, ms: 'yes', php: '8.3' }
    services:
      mysql:
        image: mariadb:latest@sha256:346f3a6792bf88014a9d9290927c12c13522a50e0e7e6d40aaa9add73df0bcc6
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MARIADB_INITDB_SKIP_TZINFO: 1
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test
    steps:
      - name: Check out source code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Decide whether to enable coverage
        id: coverage
        run: |
          if [ "${{ matrix.config.coverage }}" = "yes" ]; then
            echo "coverage=pcov" >> "${GITHUB_OUTPUT}"
            echo 'ini=pcov.directory=inc, pcov.exclude="~/(vendor|tests)/~"' >> "${GITHUB_OUTPUT}"
          else
            echo "coverage=none" >> "${GITHUB_OUTPUT}"
            echo "ini=opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M" >> "${GITHUB_OUTPUT}"
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # 2.31.1
        with:
          coverage: ${{ steps.coverage.outputs.coverage }}
          ini-values: ${{ steps.coverage.outputs.ini }}
          php-version: ${{ matrix.config.php }}
        env:
          fail-fast: 'true'

      - name: Install PHP dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # 3.0.0

      - name: Set up WordPress and WordPress Test Library
        uses: sjinks/setup-wordpress-test-library@0590797bb1242f984f15c964a31e21f01c918383 # v2.1.1
        with:
          version: ${{ matrix.config.wp }}

      - name: Set up multisite mode
        run: echo "WP_MULTISITE=1" >> "${GITHUB_ENV}"
        if: matrix.config.ms == 'yes'

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h 127.0.0.1 -P ${{ job.services.mysql.ports[3306] }} --silent; do
            sleep 1
          done
        timeout-minutes: 1

      - name: Run tests
        run: |
          OPTIONS=
          if [ "${{ steps.coverage.outputs.coverage }}" != 'none' ]; then
            OPTIONS="$OPTIONS --coverage-clover=clover.xml"
          fi
          vendor/bin/phpunit --order-by=random ${OPTIONS}

      - name: Upload coverage report
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
          flags: unittests
        if: ${{ steps.coverage.outputs.coverage != 'none' }}
